baseURL = "http://example.org/"
languageCode = "en-us"
title = "Coming Soon"
theme = "coming-soon"

[seo]
  GTMID = ""
  metaTitle = ""
  metaDescription = ""

[params]
  # 1 - Full-width Image, 2 - Two Column, 3 - Two image
  themeOption = 1
  enableForm = 1
  enableMap = 1
  [params.map]
    APIKey = ""
    coordsLat = 45.819790
    coordsLong = -122.700560
    zoom = 14
  [params.style]
    primary = "#B79F39"
    secondary = "#facade"
    bodyBg = "#2b2e34"
    bodyColor = "#ffffff"
    bgCustom = "#294954"
    fontEmbed = '<link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap" rel="stylesheet">'
    fontFamily = "'Roboto Condensed', sans-serif"
